Implement tasks 01-15
skynetplace/TwentyMethods pull request #2
Opened 2024-02-06 17:23 UTC by skynetplace

Implemented and refactored tasks from 1 to 15 inclusive.

2024-02-06 20:11 UTC, BogdanParashchak requested changes
minor changes to be done

2024-02-06 20:11 UTC, BogdanParashchak commented on src/main/java/com/honcharenko/TwentyMethods.java
> +        return year % 4 == 0;
1. check logic
2. chack for unnessesary 'else'

2024-02-06 20:11 UTC, BogdanParashchak commented on src/main/java/com/honcharenko/TwentyMethods.java
> +    public static void bubblySortIntArrayInAscendingOrder(int[] ints) {
bubbleSortIntArrayInAscendingOrder

2024-02-06 20:11 UTC, BogdanParashchak commented on src/main/java/com/honcharenko/TwentyMethods.java
> +        int[] resultIntArray = new int[firstIntArray.length];
not needed
write result into one of input arrays

2024-02-06 20:11 UTC, BogdanParashchak commented on src/main/java/com/honcharenko/TwentyMethods.java
> +// 16) Принимает два массива интов, возвращает массив из елементов, которые не совпадают в массивах.
delete

2024-02-06 20:11 UTC, BogdanParashchak commented on src/main/java/com/honcharenko/TwentyMethods.java
> +    // 1) Принимает массив чаров, выводит его на экран.
replace with javadoc in the whole class

2024-02-06 20:11 UTC, BogdanParashchak commented on pom.xml
replace with javadoc in the whole class

2024-02-06 20:11 UTC, BogdanParashchak commented on src/main/java/com/honcharenko/Starter.java
replace with javadoc in the whole class

2024-02-06 20:11 UTC, BogdanParashchak commented on src/main/java/com/honcharenko/TwentyMethods.java
replace with javadoc in the whole class

2024-02-07 09:52 UTC, diamandv commented on src/main/java/com/honcharenko/TwentyMethods.java
> +    public static int searchFirstIndexOfValueInArray(int[] ints, int searchValue) {
searchFirstIndexOfValueInArray -> findFirstIndexOfSearchingValueInArray

2024-02-07 10:28 UTC, diamandv reviewed
.

2024-02-07 13:24 UTC, skynetplace commented on pom.xml
> +    <artifactId>TwentyMethods</artifactId>
Done

2024-02-07 13:25 UTC, skynetplace commented on src/main/java/com/honcharenko/TwentyMethods.java
> +    public static int getMaxIntByTernary(int firstNumber, int secondNumber) {
Done

2024-02-07 13:25 UTC, skynetplace commented on src/main/java/com/honcharenko/TwentyMethods.java
> +    public static int getMaxIntByBranching(int firstNumber, int secondNumber) {
Done

2024-02-07 13:27 UTC, skynetplace commented on src/main/java/com/honcharenko/TwentyMethods.java
> +        }
Done

2024-02-07 13:28 UTC, skynetplace commented on src/main/java/com/honcharenko/TwentyMethods.java
> +        } else {
Done

2024-02-07 13:39 UTC, skynetplace commented on src/main/java/com/honcharenko/TwentyMethods.java
> +    public static int calculateFactorialRecursive(int number) {
Done

2024-02-07 13:43 UTC, skynetplace commented on src/main/java/com/honcharenko/TwentyMethods.java
> +        return year % 4 == 0;
Fixed

2024-02-07 13:46 UTC, skynetplace commented on src/main/java/com/honcharenko/TwentyMethods.java
> +    public static void bubblySortIntArrayInAscendingOrder(int[] ints) {
Done

2024-02-07 13:51 UTC, skynetplace commented on src/main/java/com/honcharenko/TwentyMethods.java
> +        int[] resultIntArray = new int[firstIntArray.length];
Done

2024-02-07 13:52 UTC, skynetplace commented on src/main/java/com/honcharenko/TwentyMethods.java
> +// 16) Принимает два массива интов, возвращает массив из елементов, которые не совпадают в массивах.
Done

2024-02-07 13:58 UTC, skynetplace commented on pom.xml
File without comments. Done

2024-02-07 14:04 UTC, skynetplace commented on src/main/java/com/honcharenko/TwentyMethods.java
Done

2024-02-07 14:13 UTC, skynetplace commented on src/main/java/com/honcharenko/TwentyMethods.java
> +    public static int searchFirstIndexOfValueInArray(int[] ints, int searchValue) {
Done

2024-02-07 14:14 UTC, skynetplace commented on src/main/java/com/honcharenko/TwentyMethods.java
> +    public static int searchLastIndexOfValueInArray(int[] ints, int searchValue) {
Done

2024-02-07 15:31 UTC, BogdanParashchak commented on src/main/java/com/honcharenko/TwentyMethods.java
> +        }
else if -> if

2024-02-07 15:33 UTC, BogdanParashchak requested changes

2024-02-07 15:33 UTC, BogdanParashchak commented on src/main/java/com/honcharenko/TwentyMethods.java
> +        } else if (secondNumber >= firstNumber && secondNumber >= thirdNumber) {
if (secondNumber >= firstNumber && secondNumber >= thirdNumber) {

2024-02-07 15:55 UTC, skynetplace commented on src/main/java/com/honcharenko/TwentyMethods.java
> +        } else if (secondNumber >= firstNumber && secondNumber >= thirdNumber) {
Fixed

2024-02-08 13:47 UTC, diamandv approved these changes

2024-02-08 13:47 UTC, merged