JEP-26 Implement tasks 16-19
skynetplace/TwentyMethods pull request #3
Opened 2024-02-18 18:53 UTC by skynetplace

2024-02-18 20:18 UTC, BogdanParashchak requested changes

2024-02-18 20:18 UTC, BogdanParashchak commented on src/main/java/com/honcharenko/TwentyMethods.java
> +
replace this logic using String class

2024-02-18 20:18 UTC, BogdanParashchak commented on src/main/java/com/honcharenko/Starter.java
> +        System.out.println("\n\n19) Принимает 2 массива чаров, проверяет есть ли в 1 массиве такая же последовательность символов, которую представляет собой второй массив. Возвращает булеан.");
add cases:
negative scenario
1st array is empty
2nd array isEmpty

2024-02-18 20:18 UTC, BogdanParashchak commented on src/main/java/com/honcharenko/Starter.java
> +        int int_3 = 0;
int arraySize = 10;
int lowerBound=-5;
int upperBound=0;

2024-02-18 20:18 UTC, BogdanParashchak commented on src/main/java/com/honcharenko/TwentyMethods.java
> +    }
try to find another way not to make O(n*n) algorithm complexity

2024-02-18 20:18 UTC, BogdanParashchak commented on src/main/java/com/honcharenko/Starter.java
> +        char[] array2 = {'c', 'd'};
fisstArray
secondArray

2024-02-18 20:18 UTC, BogdanParashchak commented on src/main/java/com/honcharenko/Starter.java
> +        }
System.out.println(Arrays.toString(reversedIntArray));

2024-02-18 20:18 UTC, BogdanParashchak commented on src/main/java/com/honcharenko/Starter.java
>  public class Starter {
![image](https://github.com/skynetplace/TwentyMethods/assets/86907923/89623822-fe39-40eb-8972-cfe3e1004dfd)
do not oversize

2024-02-18 21:16 UTC, diamandv reviewed
can not add something new to this review, except - please, delete unnessesery lines (115, 280)

2024-02-20 09:33 UTC, skynetplace commented on src/main/java/com/honcharenko/TwentyMethods.java
> +    }
Done.

2024-02-20 09:39 UTC, skynetplace commented on src/main/java/com/honcharenko/Starter.java
> +        int int_3 = 0;
Done.

2024-02-20 09:47 UTC, skynetplace commented on src/main/java/com/honcharenko/Starter.java
>  public class Starter {
Done.

2024-02-20 10:08 UTC, skynetplace commented on src/main/java/com/honcharenko/TwentyMethods.java
> +        int[] ints = new int[size];
Done.

2024-02-20 11:39 UTC, BogdanParashchak commented on src/main/java/com/honcharenko/TwentyMethods.java
> +    }
refactor the task:
1. compare index-to-index
2. validate imput for emptiness
3. start with comparing of input arrays lengths

2024-02-21 20:31 UTC, skynetplace commented on src/main/java/com/honcharenko/Starter.java
> +        System.out.println("\n\n18) Принимает 3 инта: размер выходного массива, нижняя граница, верхняя граница. Возвращает массив интов заданой длинный, который содержит случайные числа от нижней гр
Done.

2024-02-21 20:31 UTC, skynetplace commented on src/main/java/com/honcharenko/TwentyMethods.java
> +
Done.

2024-02-21 20:31 UTC, skynetplace commented on src/main/java/com/honcharenko/TwentyMethods.java
> +
Done.

2024-02-21 20:31 UTC, skynetplace commented on src/main/java/com/honcharenko/Starter.java
> +        System.out.println("\n\n19) Принимает 2 массива чаров, проверяет есть ли в 1 массиве такая же последовательность символов, которую представляет собой второй массив. Возвращает булеан.");
Done.

2024-02-21 20:31 UTC, skynetplace commented on src/main/java/com/honcharenko/TwentyMethods.java
> +    }
Done.

2024-02-21 20:32 UTC, skynetplace commented on src/main/java/com/honcharenko/Starter.java
> +        }
Done.

2024-02-21 20:33 UTC, skynetplace commented on src/main/java/com/honcharenko/Starter.java
> +        char[] array2 = {'c', 'd'};
Done.

2024-02-22 07:04 UTC, BogdanParashchak commented on src/main/java/com/honcharenko/TwentyMethods.java
> +    }
OK

2024-02-22 07:08 UTC, BogdanParashchak commented on src/main/java/com/honcharenko/TwentyMethods.java
> +        } else if (lowerBound > upperBound) {
delete this `else`

2024-02-22 07:08 UTC, BogdanParashchak commented on src/main/java/com/honcharenko/Starter.java
> +        System.out.println("\n\n18) Принимает 3 инта: размер выходного массива, нижняя граница, верхняя граница. Возвращает массив интов заданой длинный, который содержит случайные числа от нижней гр
OK

2024-02-22 07:08 UTC, BogdanParashchak commented on src/main/java/com/honcharenko/TwentyMethods.java
> +
OK

2024-02-22 07:10 UTC, BogdanParashchak commented on src/main/java/com/honcharenko/TwentyMethods.java
> +    }
I dont see in last commit

2024-02-22 07:12 UTC, BogdanParashchak commented on src/main/java/com/honcharenko/Starter.java
> +        char[] array2 = {'c', 'd'};
OK

2024-02-22 07:13 UTC, BogdanParashchak commented on src/main/java/com/honcharenko/Starter.java
> +        }
OK

2024-02-22 11:27 UTC, skynetplace commented on src/main/java/com/honcharenko/TwentyMethods.java
> +    }
Rewrited 16's method.

2024-02-22 12:45 UTC, BogdanParashchak approved these changes

2024-02-22 12:53 UTC, skynetplace commented on src/main/java/com/honcharenko/Starter.java
> +        TwentyMethods.printCharArray(chars);
Done.

2024-02-22 12:54 UTC, skynetplace commented on src/main/java/com/honcharenko/TwentyMethods.java
> +            return false;
Done.

2024-02-23 11:22 UTC, merged

2024-03-11 10:57 UTC, skynetplace commented on src/main/java/com/honcharenko/TwentyMethods.java
>      /**
Done